# Generated by Django 5.2.4 on 2025-08-05 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_cusratingfeedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('SELECT', 'SELECT'), ('RESTAURANT', 'RESTAURANT'), ('CUSTOMER', 'CUSTOMER'), ('ADMIN', 'ADMIN')], default='SELECT'),
        ),
    ]
