# Generated by Django 5.2.3 on 2025-07-07 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_alter_fooditemsmodel_item_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditemsmodel',
            name='prod_code',
            field=models.IntegerField(default=100),
        ),
    ]
