# Generated by Django 5.2.3 on 2025-07-07 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditemsmodel',
            name='item_image',
            field=models.CharField(default='https://cdn.dribbble.com/userupload/22570626/file/original-379b4978ee41eeb352e0ddacbaa6df96.jpg', max_length=500),
        ),
    ]
