# Generated by Django 5.2.4 on 2025-07-30 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_fooditemsmodel_restaurant_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditemsmodel',
            name='admin',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
