# Generated by Django 5.2.3 on 2025-07-07 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_fooditemsmodel_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditemsmodel',
            name='item_description',
            field=models.CharField(default='Lorem, ipsum dolor sit amet consectetur adipisicing elit. Explicabo magni, nihil assumenda sit praesentium repellendus autem culpa aliquid sequi beatae eveniet voluptatum exercitationem a aspernatur, illo placeat fugiat ducimus voluptas.', max_length=500),
        ),
    ]
